HEX
00FFFFFF CONSTANT WHITE
3E8FA000 CONSTANT FRAMEBUFFER
00000000 CONSTANT BLACK 
00FF0000 CONSTANT ROSSO
00FFD700 CONSTANT YELLOW
007FFF00 CONSTANT VERDE


: DOWN  2DUP ! 1000 + ; 

: RIGHT  2DUP ! 4 + ; 

VARIABLE BOX_COUNTER

: 0BOX_COUNTER 0 BOX_COUNTER ! ; 
0BOX_COUNTER

VARIABLE NLINE
1 NLINE !
: +NLINE NLINE @ 1 + NLINE ! ;

: FIRST FRAMEBUFFER 100 4 * + 180 1000 * + ;
: SECOND FRAMEBUFFER 200 4 * + 180 1000 * + ;
: THIRD FRAMEBUFFER 300 4 * + 180 1000 * + ;

: +BOX_COUNTER BOX_COUNTER @ 1 + BOX_COUNTER ! ;

: LINEADX
	BEGIN BOX_COUNTER @ 51 < WHILE +BOX_COUNTER RIGHT REPEAT 0BOX_COUNTER DROP DROP
;

: LINEADOWN
	BEGIN BOX_COUNTER @ 51 < WHILE +BOX_COUNTER DOWN REPEAT 0BOX_COUNTER DROP DROP
;

: COLORA
	BEGIN BOX_COUNTER @ 50 < WHILE 
	+BOX_COUNTER
	RIGHT
	REPEAT 0BOX_COUNTER DROP DROP	
;

: BOX_INIT_FIRST 
	VERDE FIRST LINEADX
	VERDE FIRST 50 1000 * + LINEADX
	VERDE FIRST 51 4 * + LINEADOWN
	VERDE FIRST LINEADOWN
;

: BOX_INIT_SECOND
	VERDE SECOND LINEADX
	VERDE SECOND 50 1000 * + LINEADX
	VERDE SECOND 51 4 * + LINEADOWN
	VERDE SECOND LINEADOWN
;

: BOX_INIT_THIRD
	VERDE THIRD LINEADX
	VERDE THIRD 50 1000 * + LINEADX
	VERDE THIRD 51 4 * + LINEADOWN
	VERDE THIRD LINEADOWN
;

: BOX_INIT  
	BOX_INIT_FIRST 
	BOX_INIT_SECOND
	BOX_INIT_THIRD 
;

BOX_INIT

: BOX_FIRST_WHITE
	WHITE FIRST 4 1000 + + COLORA	
	BEGIN NLINE @ 50 <
	WHILE 
		WHITE FIRST 4 + 1000 NLINE @ * + COLORA
		+NLINE
	REPEAT
	1 NLINE !
;

: BOX_SECOND_YELLOW
	YELLOW SECOND 4 1000 + + COLORA	
	BEGIN NLINE @ 50 <
	WHILE 
		YELLOW SECOND 4 + 1000 NLINE @ * + COLORA
		+NLINE
	REPEAT
	1 NLINE !
;

: BOX_THIRD_ROSSO
	ROSSO THIRD 4 1000 + + COLORA	
	BEGIN NLINE @ 50 <
	WHILE 
		ROSSO THIRD 4 + 1000 NLINE @ * + COLORA
		+NLINE
	REPEAT
	1 NLINE !
;

: BOX_FIRST_BLACK
	BLACK FIRST 4 1000 + + COLORA	
	BEGIN NLINE @ 50 <
	WHILE 
		BLACK FIRST 4 + 1000 NLINE @ * + COLORA
		+NLINE
	REPEAT
	1 NLINE !
;

: BOX_SECOND_BLACK
	BLACK SECOND 4 1000 + + COLORA	
	BEGIN NLINE @ 50 <
	WHILE 
		BLACK SECOND 4 + 1000 NLINE @ * + COLORA
		+NLINE
	REPEAT
	1 NLINE !
;

: BOX_THIRD_BLACK
	BLACK THIRD 4 1000 + + COLORA	
	BEGIN NLINE @ 50 <
	WHILE 
		BLACK THIRD 4 + 1000 NLINE @ * + COLORA
		+NLINE
	REPEAT
	1 NLINE !
;

: FIRST_BOX
	BOX_FIRST_WHITE 
	BOX_SECOND_BLACK 
	BOX_THIRD_BLACK
;

: SECOND_BOX 
	BOX_FIRST_BLACK
	BOX_SECOND_YELLOW
	BOX_THIRD_BLACK
;

: FINAL_BOX 
	BOX_FIRST_WHITE
	BOX_SECOND_YELLOW
	BOX_THIRD_ROSSO
;

: THIRD_BOX 
	BOX_FIRST_BLACK 
	BOX_SECOND_BLACK
	BOX_THIRD_ROSSO
;



: ALL_BLACK
	BOX_FIRST_BLACK 
	BOX_SECOND_BLACK
	BOX_THIRD_BLACK
;


