HEX

VARIABLE COMPARISON
VARIABLE COMP1

7A120 CONSTANT HALFSEC
F424 CONSTANT AGGSEC

08224000 GPFSEL1 !
12040000 GPFSEL2 !

0 COMPARISON !
0 COMP1 !

: RED 04000000 ;
: GREEN 80000 ;

: LED GPSET0 GPCLR0 ;

: ON DROP ! ;
: OFF NIP ! ;

: LAYOUTSIS 0 1 LCDSTRING ;
 
: INCREMENT SYSCLO @ HALFSEC + COMPARISON ! ;
: INC SYSCLO @ AGGSEC + COMP1 ! ;


: HALFSLEEP HEX INCREMENT BEGIN SYSCLO @ COMPARISON @ < WHILE REPEAT DROP DECIMAL ;
: SLEEP HEX INC BEGIN SYSCLO @ COMP1 @ < WHILE REPEAT DROP DECIMAL ;

: 3HALFSLEEP HALFSLEEP HALFSLEEP HALFSLEEP ;
: 2HALFSLEEP HALFSLEEP HALFSLEEP ; 

DECIMAL


VARIABLE TIME
: RESET 0 TIME ! ;
RESET

: PRINTMIN 4 0 LCDNUMBER ;
: PRINTSEC 7 0 LCDNUMBER ;
: PRINTCOLONMIN HEX S" :" 2 0 LCDSTRING ;
: PRINTCOLONSEC HEX S" :" 5 0 LCDSTRING ;

DECIMAL 
: ZEROSEC TIME @ 60 /MOD SWAP 10 < IF 0 6 0 LCDNUMBER THEN ;

: ZEROMIN TIME @ 60 /MOD 600 < IF 0 3 0 LCDNUMBER THEN ;

: ZEROHOUR TIME @ 3600 < IF 0 0 0 LCDNUMBER 0 1 0 LCDNUMBER THEN ;

: TIMER_INIT ZEROHOUR PRINTCOLONMIN ZEROMIN PRINTCOLONSEC ZEROSEC ;

: LYT TIME @ 60 /MOD PRINTMIN PRINTSEC TIMER_INIT ;

: INCTIME GPIO0 LEVEL 0> IF TIME @ 1 + TIME ! LYT SLEEP THEN ;

: DECTIME GPIO13 LEVEL 0> TIME @ 0> AND IF TIME @ 1 - TIME ! LYT SLEEP THEN ;

: SET_TIME S" INSERISCI TEMPO" LAYOUTSIS INCTIME DECTIME ;

: STOP GPIO21 LEVEL 0> IF S" TIMER ARRESTATO" LAYOUTSIS THIRD_BOX 3HALFSLEEP LCDCLR RESET 2HALFSLEEP ALL_BLACK THEN ;

: DECREMENT TIME @ 0> IF TIME @ 1 - TIME ! ELSE S" TEMPO SCADUTO" LAYOUTSIS FINAL_BOX 3HALFSLEEP LCDCLR HALFSLEEP THEN DROP ;

: PAUSA BEGIN GPIO6 LEVEL 0> WHILE S" SONO IN PAUSA" LAYOUTSIS SECOND_BOX 3HALFSLEEP REPEAT ;

: BLINKGREENLED GREEN LED ON HALFSLEEP GREEN LED OFF LCDCLR HALFSLEEP ;
: BLINKREDLED RED LED ON HALFSLEEP RED LED OFF LCDCLR HALFSLEEP ;

: BLINKLED DECIMAL DECREMENT TIME @ 10 > IF LYT BLINKGREENLED S" TIMER AVVIATO" LAYOUTSIS ELSE TIME @ 0= IF RED LED OFF ELSE LYT BLINKREDLED S" TIMER AVVIATO" LAYOUTSIS THEN THEN ;

: GOON FIRST_BOX BEGIN GPIO6 LEVEL 0= GPIO21 LEVEL 0= AND WHILE BLINKLED  REPEAT ;

: COUNTDOWN BEGIN GPIO20 LEVEL 0> TIME @ 0> AND WHILE GOON PAUSA REPEAT ;

: TEST BEGIN TRUE WHILE SET_TIME STOP COUNTDOWN REPEAT ;


LCD-INIT
TEST

